### ISSUE TITLE
Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by dwellons** [dwellons/DonationLog#1]
@pawaitemadisoncollege I have checkpoint 1 ready for review! I will double check that you see this after I invited you to the repository

**Comment by pawaitemadisoncollege** [comment]
Hi @dwellons! 

Thanks for sharing your indie project checkpoint 1! You are off to a very solid start (I see some code already!) and have such a meaningful project to work on. 

Following are my observations, suggestions and questions:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it.

- [ ] This might be a little nitpicky, but I noticed some inconsistency in the perspective and think this would read better if it were consistent. Either describe it from the "we" perspective or 3rd person. You might read it out loud to see if that jumps out at you too.
- [ ] "will let donations record donations" should this be "will let volunteers record donations" or staff or?? 
- [ ] Technology list - did we talk about a service/api to use? Maybe javamail for emailing reports?

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example, full CRUD. That said, sometimes I am too optimistic/ambitious, so let's both keep an eye on how things progress and what, if anything needs to be delayed to V2. 

- [ ] The language using Donations as a kind of user in a user story felt odd to me. Maybe this is how your organization refers to the people entering donations? Maybe worker, volunteer, donation collector/receiver?
- [ ] Should have a sign out user story too (it's in the screens)
- [ ] Should any user need to log in? Is there a need to track who entered a donation?
- [ ] If I make a mistake entering a donation, do I need an administrator to edit it, or should I be able to edit any donations that I entered?
- [ ] I think the goal here is a single organization. Something to consider - could the same instance of the website be used by multiple organizations? Maybe that is a later version?

**Project plan**

Looks familiar! 

- [ ] I noticed api/web service research is checked off. Did that happen? 
- [ ] Keep modifying the plan (adding tasks) as you learn more!  What's not covered yet?

**Screen design**

BEAUTIFUL! 

- [ ] I had this in my original screens too and need to fix it in the actual jsps:  a link for Log in and Log out probably do not both need to be showing at the same time. I'd go with a LogIn link that toggles to LogOut if the user is logged in.  
- [ ] When comparing user stories to screens, I didn't see screens for editing or deleting donations. 
- [ ] Would it make sense to store a donor's email so that it doesn't have to be entered manually when sending a report?
- [ ] The problem statement refers to value and amounts of donations. Are those captured in the screen design?

**Reflection statements/Time Log**

Great work consistently tracking!

- [ ] You do not have to use three documents for this unless you find it beneficial- one is fine. I showed three variations in the demo project to give folks a few options. 

**Other**

- [ ] I noticed some logs and property files which could contain information like usernames, passwords, etc. It would be a good idea to remove these from GitHub and add them to .gitignore. If you aren't able to find the details on how to do this, please post in slack as I'm sure other will run into this too!

**Comment by dwellons** [comment]
@pawaitemadisoncollege hello! I corrected most of these but the other ones thought we should decide more before moving forward. 

Should any user need to log in? Is there a need to track who entered a donation?
I think this could go either way, I can see a need for tracking who entered the donations, but my concern is that everyone would need a username then and I think that would start to get to be too much for some of the people that would be using it. I had an idea that there could just be a "volunteer" username that they could share, its not a good idea to have a shared user like that but in this situation it might be a solution. Something I'm thinking of while typing this too is that maybe there is just an empty field when logging a donation for them to put initials or their name into. And then the administrators would still be the ones logging in to modify if they had to. 

If I make a mistake entering a donation, do I need an administrator to edit it, or should I be able to edit any donations that I entered?
Would there be a way to be able to modify maybe the last 2-5 entered donations in the situation of not being a signed in user?

Would it make sense to store a donor's email so that it doesn't have to be entered manually when sending a report?
I think this is a good idea, and it could maybe pre-load it into a form field so that it can still be edited if its changed.

**Comment by pawaitemadisoncollege** [comment]
Sorry for the slow reply on this - I think you are traveling this week - hope it's going well!!!! 

**User log in** - I think the shared username is a legit solution!  While I agree that in many cases a shared username is not a good idea, I also understand that sometimes it does make it easy. I like the "add your initials" idea as well.  We (I) also need to remember this is V1, and it doesn't have to do everything (yet). 

**Editing ** - I really like that idea of being able to change the last X number of donations. Great thought there, Darin!
